# 工作流名称
name: Build Docker Image - build

# push tag 时触发执行
on:
  workflow_dispatch:
  push:
    tags:
      - v*

# 定义环境变量, 后面会使用
# 定义 DOCKERHUB_REPO 标记 docker hub repo 名称
env:
  DOCKERHUB_REPO: yuchunyu97/vllm-openai

jobs:
  main:
    # 在 Ubuntu 上运行
    runs-on: ubuntu-latest
    steps:
      - run: sudo rm -rf /usr/share/dotnet
      - run: sudo rm -rf /opt/ghc
      - run: sudo rm -rf "/usr/local/share/boost"
      - run: sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      
      # git checkout 代码
      - name: Checkout
        uses: actions/checkout@v2
      # 设置 QEMU, 后面 docker buildx 依赖此.
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      # 设置 Docker buildx, 方便构建 Multi platform 镜像
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # 登录 docker hub
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: yuchunyu97
          password: yuchunyu97
      # 通过 git 命令获取当前 tag 信息, 存入环境变量 APP_VERSION
      - name: Generate App Version
        run: echo APP_VERSION=`git describe --tags --always` >> $GITHUB_ENV
      # 构建 Docker 并推送到 Docker hub
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPO }}:build-${{ env.APP_VERSION }}
